// Generated by SolidPython 1.1.3 on 2023-04-08 02:27:49
$fn =128;


union() {
	difference() {
		cylinder(h = 10, r = 2.5000000000);
		cylinder(h = 10, r = 0.2500000000);
	}
	translate(v = [0, 0, 10]) {
		cylinder(h = 1.0000000000, r = 1.2500000000);
	}
}