// Generated by SolidPython 1.1.3 on 2023-04-08 02:27:49
$fn =128;


union() {
	difference() {
		cylinder(h = 14, r = 3.5000000000);
		cylinder(h = 14, r = 0.3500000000);
	}
	translate(v = [0, 0, 14]) {
		cylinder(h = 1.4000000000, r = 1.7500000000);
	}
}