// Generated by SolidPython 1.1.3 on 2023-04-08 02:27:49
$fn =128;


union() {
	difference() {
		cylinder(h = 16, r = 4.0000000000);
		cylinder(h = 16, r = 0.4000000000);
	}
	translate(v = [0, 0, 16]) {
		cylinder(h = 1.6000000000, r = 2.0000000000);
	}
}