// Generated by SolidPython 1.1.3 on 2023-04-08 02:27:49
$fn =128;


union() {
	difference() {
		cylinder(h = 17, r = 4.2500000000);
		cylinder(h = 17, r = 0.4250000000);
	}
	translate(v = [0, 0, 17]) {
		cylinder(h = 1.7000000000, r = 2.1250000000);
	}
}