// Generated by SolidPython 1.1.3 on 2023-04-08 02:27:49
$fn =128;


union() {
	difference() {
		cylinder(h = 13, r = 3.2500000000);
		cylinder(h = 13, r = 0.3250000000);
	}
	translate(v = [0, 0, 13]) {
		cylinder(h = 1.3000000000, r = 1.6250000000);
	}
}