// Generated by SolidPython 1.1.3 on 2023-04-08 02:27:49
$fn =128;


union() {
	difference() {
		cylinder(h = 15, r = 3.7500000000);
		cylinder(h = 15, r = 0.3750000000);
	}
	translate(v = [0, 0, 15]) {
		cylinder(h = 1.5000000000, r = 1.8750000000);
	}
}