// Generated by SolidPython 1.1.3 on 2023-04-08 02:27:49
$fn =128;


union() {
	difference() {
		cylinder(h = 19, r = 4.7500000000);
		cylinder(h = 19, r = 0.4750000000);
	}
	translate(v = [0, 0, 19]) {
		cylinder(h = 1.9000000000, r = 2.3750000000);
	}
}