// Generated by SolidPython 1.1.3 on 2023-04-08 03:38:03

difference(){
import(file = "BOTTLETEST.stl", origin = [0, 0]);
    
    translate([0,0,1.7])
    cube(size=[10,10,10],center= true);
    
    
    
    
    
}